add lab 3 code
Orest0501/-lab3-Orest pull request #1
Opened 2021-10-28 19:35 UTC by Orest0501

You need to create text that should be displayed next to the likes. Implement a function like [String]> String, which should use an input array containing the names of people who like the photo

2021-10-31 19:10 UTC, Olegbdnr approved these changes

2021-12-19 10:21 UTC, zveres-ss requested changes

2021-12-19 10:21 UTC, zveres-ss commented on lab3.cpp
> +    int array[15] = { 0 };
make 15 and 2 as constants

2021-12-19 10:21 UTC, zveres-ss commented on lab3.cpp
> +    char result1[200] = "";
200 should be declared either as constant or #define

2021-12-19 10:21 UTC, zveres-ss commented on lab3.cpp
> +    int m = 1, i = 0;
what m variable name means?

2021-12-19 10:21 UTC, zveres-ss commented on lab3.cpp
> +        }
same code as in lines 46-50

2022-03-27 14:59 UTC, merged